In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import LabelEncoder
from sklearn.cross_decomposition import PLSRegression

In [2]:
z_score_df = pd.read_pickle('matrix_Coimbra_threshold.pkl')

In [3]:
z_score_df

Protein.Group,A0A075B6H7,A0A075B6K5,A0A075B6P5;P01615;A0A087WW87;P01614,A0A075B6S5;A0A0C4DH67;A0A0C4DH69,A0A0A0MRZ8;P04433,A0A0A0MS15,A0A0B4J1U7,A0A0B4J1X8,A0A0B4J1Y9,A0A0B4J2B5,...,Q9UBP4,Q9UBX5,Q9UKI9;P09086;P14859,Q9ULB1,Q9Y4C0,Q9Y646,Q9Y6R7,cRAP-P00760,cRAP-P0AEY0,cRAP-P42212
109094,-0.235900,0.368910,-0.001399,-0.250872,-0.547748,-1.042582,-0.160501,-0.143467,0.005032,-0.948622,...,-0.414465,-1.411198,-0.603788,0.279622,-0.086622,-0.504171,-0.679232,-1.199426,-0.533962,-0.300272
103208,-0.477700,-0.881979,-0.168997,-0.985325,-0.561344,0.057938,-1.014755,-0.658864,-0.468966,-0.312457,...,-0.327057,-0.636241,0.490588,-0.484750,-0.389092,0.438867,-0.503038,-0.962731,-0.401852,-0.413514
106086,0.111044,0.284163,0.250087,-0.378412,-0.227504,-0.301630,-0.503469,-0.126363,0.518555,-0.118962,...,0.571070,-0.469992,0.153253,1.518716,1.494299,1.107409,0.174871,-0.447917,-0.783628,-0.764881
105634,0.990569,1.625988,1.662398,0.913341,1.220554,0.855728,-1.121883,0.649082,0.438595,1.152746,...,0.852665,-0.976623,0.658613,-1.926108,-0.802330,-0.189145,-1.002443,-0.748056,-1.934922,-1.830716
106008,-0.204214,-0.317213,0.782627,0.151888,0.002889,-1.165807,0.532662,0.500921,0.245322,0.025983,...,1.232430,-0.041504,0.556811,0.592066,-0.567734,-0.174536,0.419020,0.335909,-0.934451,-0.797986
110203,-0.802347,-0.716040,-0.989515,-0.617416,-0.383789,-0.380295,0.942366,-0.452439,-0.674361,-1.005461,...,1.351128,-0.721190,-0.218162,1.013610,0.867521,-0.380777,-0.600125,1.152790,0.639728,0.906787
108382,0.285327,0.618069,0.324381,-0.185258,-0.651542,-0.048090,1.203597,-0.527076,0.215549,-0.390191,...,0.301279,-0.769686,0.267671,-0.659311,-0.598041,0.530081,0.950284,-0.515290,-0.955682,-0.508277
104968,-0.237161,0.360176,0.078879,-0.085830,-0.863270,-0.230325,0.556989,0.287000,-0.682868,-0.124799,...,-0.248154,-1.584071,-0.278365,0.214096,-0.240083,1.064027,1.397432,-0.033633,0.046453,-0.029472
107018,-0.698645,0.635296,0.293461,-0.506870,-0.354595,-0.043427,0.835735,0.361479,0.456846,0.267781,...,-0.716436,-0.847352,0.546170,0.055156,0.131578,-1.434655,-1.457332,-0.263177,0.694673,0.681358
109456,-1.728946,-2.005236,-1.509203,-1.384965,-1.411332,-2.031558,-2.276153,-1.226211,-1.741858,-1.582536,...,0.540750,-0.422296,-0.586496,0.932252,0.614257,-0.188065,-1.702706,-0.344019,0.425366,0.530735
108259,1.151811,0.010273,0.785207,1.621965,0.707386,-0.469418,1.132516,0.751636,-0.439185,0.990074,...,0.146771,-0.436765,0.442554,0.373210,0.807889,0.258491,-0.181197,-0.282272,0.112438,0.450614
109500,0.912697,0.703382,0.315010,-0.134125,-0.136857,0.720079,0.349035,0.556944,1.023019,0.394589,...,-0.429593,-0.734038,-2.816625,1.098277,1.674586,-0.226459,0.564465,0.335909,0.386453,0.579134
106628,-1.167058,-0.718155,-0.964380,-1.272571,-1.339651,-1.748564,-0.319731,-2.151571,-0.659615,-1.135497,...,-0.821342,-1.249391,-0.100031,-0.803602,0.229210,0.087556,0.722772,-0.340353,-0.684035,-0.475870
108267,-1.441261,-1.305620,-0.925589,-0.694850,-1.304506,-1.146515,-0.694623,-0.118568,-1.227406,-1.696969,...,0.874713,-0.866412,-0.499678,-0.173012,0.901725,0.944503,-1.491813,0.377921,0.455626,0.848674
101072,-0.326394,-0.755058,-0.698767,-0.205668,-0.677528,-0.337805,1.012013,0.326439,-1.670909,-0.891043,...,-0.219481,0.844766,-0.514424,0.342954,0.411301,0.895842,1.608492,0.193423,0.519472,0.448585
102168,-2.465377,-1.116009,-1.536371,-2.402176,-2.467300,-0.688915,-0.470143,-2.101404,-3.002584,-2.095058,...,-0.252441,0.157905,-0.576043,0.179647,0.115727,0.750356,-1.613102,-1.490453,-0.425359,-0.469590
103321,-1.805293,-0.221172,-1.040440,-1.451248,-1.451326,-1.431014,-1.704102,-1.292627,-2.608377,-2.418590,...,0.119445,-0.622301,-0.425823,-0.397166,-0.076296,-1.331019,-1.502026,-2.199303,-0.769218,-0.765279
109466,-0.000507,0.463563,-0.916459,0.105014,-0.102011,-0.004627,-0.077058,-0.636314,0.721872,-0.651391,...,-1.890913,-0.676839,-2.488517,-1.394559,-0.265707,-0.598308,-1.053964,0.846609,1.546474,1.351581
100834,0.603061,1.237640,1.470593,0.534434,0.663875,0.778239,-0.773247,0.875574,0.413331,0.671347,...,0.225763,0.542077,0.964719,-0.225195,0.820666,1.296489,-0.791726,-2.473746,-1.820475,-1.526108
108558,0.164815,0.416175,0.214470,-0.154300,0.042223,0.133970,-0.141716,-0.475365,0.042122,-0.361028,...,-0.403073,-2.686143,0.197766,0.077174,-0.307731,-1.527946,0.083480,-0.734174,-0.976207,-0.395139
100883,0.412328,1.118845,0.336103,1.326408,0.547336,1.402570,-1.033679,-0.060962,0.928096,0.212930,...,-1.533819,1.272305,-2.624348,-1.012968,-0.585273,0.147758,0.281802,-0.091725,-0.199785,-0.339142
106531,0.408290,0.597759,0.077087,-0.254202,-0.350284,-0.508579,0.528005,-0.039898,-0.375372,0.135158,...,-0.687215,-0.007487,-0.356246,-1.171825,-0.349619,0.759156,0.105356,0.877585,0.774249,0.678552
106389,-0.200493,0.579811,-0.772889,-0.959131,-0.478254,1.057478,-0.875659,-0.375283,0.075651,0.113931,...,-2.523954,-1.576363,-0.493339,-1.080379,-1.027521,-0.229921,-1.377131,-0.142973,0.066882,0.031949
110404,0.602811,-0.098947,0.831196,0.625532,1.306440,-0.741941,-0.481342,-0.257938,0.336462,0.405049,...,0.484176,-0.327605,-0.328890,0.955130,-0.911277,1.276607,-0.104616,0.916186,0.517782,1.010009
110579,0.047186,-0.111927,-0.285122,-0.232972,-0.229697,-1.063800,1.230896,0.015772,0.129038,0.054909,...,1.164959,-1.537976,0.663065,0.129693,-0.201919,0.707734,-0.441807,0.890005,0.298729,0.619135
110073,0.421860,-0.177776,-0.118182,-0.166787,0.508851,-1.235918,0.783318,-1.292990,-0.028040,-0.296328,...,-0.773399,-0.630501,-1.304723,0.420460,0.015957,-0.014358,-0.371022,0.147540,0.350151,0.596604
107461,0.371642,1.493487,-0.578347,0.472824,0.045032,1.001121,-0.360998,1.685426,0.704907,0.344796,...,-2.170786,-0.538419,-0.932926,-1.821454,-0.523904,-0.521311,1.608135,0.813936,1.359197,1.147019
103293,1.356591,1.745024,1.479853,0.665352,1.893915,1.294236,0.866850,2.245007,1.180413,1.693345,...,-0.126995,1.127925,0.490243,-1.874530,-2.514454,-1.383748,2.335369,-0.017503,-0.010383,-0.079427
106583,0.256082,0.336098,-0.168414,-0.681555,-0.607811,-0.726044,0.373153,0.003984,-0.554310,-0.009054,...,-1.046672,-1.455237,-2.193949,-2.391107,-2.175410,-0.260201,-0.280442,-0.646180,-0.072812,-0.051526
104251,0.542634,-0.050670,-0.893721,-0.980885,-0.291388,-0.174520,0.128170,-0.818525,-0.552758,-2.034655,...,-1.417076,-1.488453,-0.973761,0.122649,-1.125008,-0.711501,0.373421,-0.691188,-0.239532,-0.251162
102434,1.022082,1.342878,-0.179525,1.264821,1.225926,1.842400,1.420266,1.077946,1.122484,0.775206,...,-1.040149,0.233883,1.300567,-1.263312,-0.842668,0.675284,0.134725,0.002302,0.417854,0.522455
102721,0.360936,0.532686,-0.168811,0.492591,0.382149,1.212417,1.841648,0.546499,1.163200,0.426634,...,0.599739,-0.340145,0.659904,-0.618273,-0.817502,1.528285,0.152328,0.254808,0.395699,0.449000
107282,0.227887,-0.367013,0.664051,0.231244,0.258376,-0.200029,-1.419562,-0.284264,-0.289122,-0.423592,...,0.370644,0.019441,0.152446,-0.823044,-1.658009,-0.064604,-0.397545,-0.743847,-0.988152,-1.009283
102037,0.295943,1.778556,0.271595,0.632567,0.627853,1.102870,-0.461337,0.578569,-0.088239,0.408335,...,-0.709899,0.592847,-2.018505,-1.698752,-1.278897,0.227275,1.162132,0.434863,0.562938,0.119871
108810,2.469936,2.682833,0.724973,1.986706,1.432592,0.626662,1.628737,1.702224,0.432749,0.078320,...,-0.657887,0.334875,-0.310717,-1.068120,-0.227593,0.016456,0.767633,1.550764,1.816246,1.526689
103698,0.366486,-0.957047,1.183487,0.327564,0.861973,1.607531,1.322892,0.515993,0.430289,0.843095,...,-0.863675,-0.025069,0.246731,0.785687,-0.262065,0.690111,1.288675,-0.161888,0.005710,-0.522462
107702,-0.539757,-1.134267,-0.079078,-0.820579,-0.223885,0.123147,-1.073102,-0.726205,-0.157876,-0.506088,...,1.451071,1.025424,1.136621,0.594784,0.580809,1.413108,1.304712,-0.686971,-0.883940,-0.324409
108726,0.314610,-0.582219,0.142174,0.255310,0.167629,1.572493,0.749807,1.286744,1.170962,0.647608,...,2.145343,1.056494,0.264909,2.092170,2.234882,0.507841,-1.437990,0.874017,0.851152,0.935824
106022,0.877938,-0.050905,1.392710,1.379604,1.194095,0.576125,1.541719,0.806676,0.493878,1.338928,...,-0.268208,0.369060,1.044213,0.956557,1.124540,0.819157,-0.725552,0.139384,-0.466113,-0.651294
105728,-1.522957,-1.947726,-1.101161,-1.379455,-1.936975,-1.349574,-0.647816,-1.517884,-1.168987,-1.480257,...,-0.443409,0.783403,-0.074605,1.678918,2.567079,1.585666,-0.125092,-0.496976,-1.134844,-1.358870
100855,0.358847,-1.179415,0.133845,0.087973,-0.097647,-1.935295,-1.218645,-0.567042,0.283956,0.488121,...,0.976961,0.381418,0.863559,1.006482,1.203975,-0.846793,-2.089748,-0.352106,-1.859145,-2.025248
106746,-0.895247,-1.422705,-1.271797,-1.074906,-0.190150,-0.469730,-1.302006,-1.658181,-0.205967,-0.185000,...,1.162429,0.080396,0.526125,2.038898,1.374946,-1.762023,-0.305325,-0.419275,-1.784047,-1.950647
103423,-0.873735,-1.165191,-0.501049,-0.722774,-0.822715,-1.786400,-0.782136,-0.528939,-0.210667,-0.531432,...,0.175054,0.287178,0.398738,0.637729,0.663341,-1.912944,-0.508451,-0.535530,-1.481084,-1.679978
100112,-2.288247,-1.448060,-1.737731,-2.357922,-2.248836,-0.811516,-1.313670,-1.190155,-1.981741,-1.242039,...,-0.683411,1.200423,0.233676,1.158687,1.686399,0.024812,1.004309,-0.424082,-0.421658,-0.525900
100596,-0.702776,-0.282658,-1.418083,-1.041339,-0.545457,-1.110478,-1.515232,-0.027551,-0.525877,-0.440960,...,0.720860,0.910816,1.454829,0.070227,0.692565,-0.222922,1.635610,-0.325578,-0.605159,-0.572892
101960,-0.168072,-0.695070,0.535845,0.108498,0.086870,0.177155,-0.707001,-0.094838,0.410865,0.741978,...,0.928698,1.334496,0.986049,0.361770,0.101365,-0.874056,-0.018845,0.582274,0.590974,0.357831
104804,-0.438253,-1.322378,-1.720507,-0.354367,-0.049678,-0.288192,0.986958,-0.799626,-0.783439,-0.240626,...,0.979369,1.186781,-0.187004,0.241842,0.477368,1.252463,-1.705941,-0.633672,-0.784542,-1.007490
100111,-1.550007,-0.435326,-1.468154,-0.177234,-1.204792,0.016155,-1.059451,-0.950846,-0.952447,-0.735888,...,0.292811,0.112834,0.637262,0.194687,0.848787,0.311225,0.502803,-2.263063,-1.651450,-2.178456
104726,-0.406172,-0.533336,-0.633898,-0.019076,-0.182641,0.638645,-0.074976,0.410338,0.244810,0.692017,...,-0.338227,1.178737,0.086144,-0.788142,-0.792171,0.528882,-0.370142,0.836237,0.685257,0.379581
105438,0.859885,0.394183,2.086597,1.514075,1.543790,1.092336,-0.194774,1.349834,2.189908,2.305962,...,0.922735,1.157755,1.000066,0.307623,-0.516268,0.465512,0.096135,1.907360,1.375199,1.121555
105080,0.776361,0.423102,1.209132,0.699607,0.957408,1.011650,-0.523137,1.034581,1.275449,1.157872,...,0.024633,1.704565,1.306679,0.423508,-0.425591,0.683172,0.420426,2.670479,2.046178,1.813174
109901,2.054818,1.107024,2.399967,2.497006,2.332115,1.189059,1.287901,2.534401,1.782179,2.014916,...,0.592302,1.914253,0.990782,1.159921,0.426080,-0.801468,0.691616,2.449358,1.261311,1.302770
109089,0.506977,1.010484,0.251427,0.682026,0.973873,1.402885,0.122024,1.384122,0.498618,1.031617,...,0.359750,0.126382,0.947869,-0.208518,-0.394365,-2.429140,1.036940,1.127824,0.442014,0.570403
103176,1.761874,0.181771,1.048163,1.328978,1.156808,0.589123,0.890450,0.337524,1.278926,1.031908,...,1.765588,1.788772,1.256090,-0.030372,-0.317248,1.697110,0.048492,0.336072,1.543870,1.405639
102357,1.092470,0.851717,1.717818,1.213268,1.240854,0.923149,0.219849,-0.485369,0.641566,1.301187,...,-0.415412,-0.081724,0.776185,0.272984,-0.042524,-1.648743,0.452162,-0.512571,1.394878,1.160459
107362,-0.549202,-0.998583,-0.008339,0.964627,0.035421,0.336681,0.232525,-0.765984,-0.535347,-0.199138,...,1.684874,0.933503,0.040539,-0.305439,-0.335648,-2.148452,0.601766,-0.077555,-0.474573,-0.673610
109522,-0.260079,0.097807,-0.807208,-0.150152,0.524276,0.130748,1.581821,0.528034,0.731672,0.311322,...,-1.594862,0.502309,-0.834472,-0.067250,-1.408280,-0.303965,0.912989,1.203681,1.694060,1.932914

In [4]:
import pickle

with open('list_groups_Coimbra.pkl', 'rb') as f:
    list_groups = pickle.load(f)

print(list_groups)

['MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD']

In [5]:
list_groups = pd.Series(list_groups)

In [6]:
def calculate_vip(pls, X):
    
    t = pls.x_scores_
    w = pls.x_weights_
    q = pls.y_loadings_
    
    p, h = w.shape
    s = np.diag(t.T @ t @ q.T @ q).reshape(h, -1)
    
    Wnorm = (w ** 2) / np.sum(w ** 2, axis=0)
    
    vip = np.sqrt(p * (Wnorm @ s) / np.sum(s))
    
    return vip.flatten()

In [7]:
def stratified_bootstrap(X, y):
    """
    Creates a bootstrap sample preserving the original class proportions.
    """
    ad_idx = np.where(y == "MCI-AD")[0]
    ct_idx = np.where(y == "MCI-CT")[0]

    ad_sample = np.random.choice(ad_idx, size=len(ad_idx), replace=True)
    ct_sample = np.random.choice(ct_idx, size=len(ct_idx), replace=True)

    indices = np.concatenate([ad_sample, ct_sample])
    np.random.shuffle(indices)

    return X.iloc[indices], y.iloc[indices]


# Settings
n_iterations = 100
feature_names = z_score_df.columns

importance_matrix = np.zeros((n_iterations, len(feature_names)))
ranking_matrix = np.zeros((n_iterations, len(feature_names)))

vip_matrix = np.zeros((n_iterations, len(feature_names)))
vip_ranking_matrix = np.zeros((n_iterations, len(feature_names)))
vip_selection_matrix = np.zeros((n_iterations, len(feature_names)))

le = LabelEncoder()
le.fit(list_groups)


# Main loop
for i in range(n_iterations):

    X_boot, y_boot = stratified_bootstrap(z_score_df, list_groups)

    # =====================
    # RANDOM FOREST 
    # =====================

    rf = RandomForestClassifier(
        n_estimators=1000,
        class_weight="balanced",
        n_jobs=-1,
        random_state=i
    )

    rf.fit(X_boot, y_boot)

    # importances
    importances = rf.feature_importances_
    importance_matrix[i] = importances

    # ranking (1 = migliore)
    ranks = (-importances).argsort().argsort() + 1
    ranking_matrix[i] = ranks

    # =====================
    # PLS-DA 
    # =====================

    # encode y
    y_encoded = le.transform(y_boot)

    pls = PLSRegression(n_components=2)
    pls.fit(X_boot, y_encoded)

    # VIP
    vip_scores = calculate_vip(pls, X_boot)
    vip_matrix[i] = vip_scores

    # ranking VIP (1 = migliore)
    vip_ranks = (-vip_scores).argsort().argsort() + 1
    vip_ranking_matrix[i] = vip_ranks
    vip_selection_matrix[i] = (vip_scores > 1).astype(int)


# Aggregazione risultati
mean_importance = importance_matrix.mean(axis=0)
mean_rank = ranking_matrix.mean(axis=0)
std_rank = ranking_matrix.std(axis=0)

mean_vip = vip_matrix.mean(axis=0)
mean_vip_rank = vip_ranking_matrix.mean(axis=0)
std_vip_rank = vip_ranking_matrix.std(axis=0)
vip_freq = vip_selection_matrix.mean(axis=0)


# DataFrame finale
importance_df = pd.DataFrame({
    "protein": feature_names,
    "importance": mean_importance,
    "mean_rank": mean_rank,
    "rank_std": std_rank
}).sort_values(by="importance", ascending=False)

vip_df = pd.DataFrame({
    "protein": feature_names,
    "VIP": mean_vip,
    "mean_rank_vip": mean_vip_rank,
    "std_rank_vip": std_vip_rank,
    "vip_freq": vip_freq
}).sort_values(by="VIP", ascending=False)

In [8]:
vip_df

    protein       VIP  mean_rank_vip  std_rank_vip  vip_freq
176  P61916  2.217911           1.20      0.489898      1.00
70   P02751  2.086182           2.90      1.734935      1.00
110  P07998  2.007868           4.86      2.993393      1.00
68   P02749  1.984973           5.07      2.458679      1.00
139  P18065  1.927461           7.27      4.061662      1.00
..      ...       ...            ...           ...       ...
186  Q13332  0.365606         197.40     40.126301      0.01
122  P0C0L5  0.365211         204.19     32.801431      0.01
179  P98160  0.343418         204.91     39.877837      0.02
124  P10451  0.326502         206.29     33.250653      0.00
104  P07333  0.321173         205.31     36.643061      0.00

[238 rows x 5 columns]

In [9]:
importance_df

        protein  importance  mean_rank   rank_std
176      P61916    0.059942       1.93   1.305795
70       P02751    0.046582       4.12   3.105737
68       P02749    0.046515       4.21   2.854102
139      P18065    0.037369       7.33   5.265083
110      P07998    0.035253       7.92   5.143306
..          ...         ...        ...        ...
62       P02675    0.000299     194.28  33.817179
7    A0A0B4J1X8    0.000286     196.34  31.975997
50       P01780    0.000283     196.33  31.677454
99       P06681    0.000280     197.12  34.731910
153      P29622    0.000272     198.28  34.465948

[238 rows x 4 columns]

In [14]:
final_df = importance_df.merge(vip_df, on="protein")
final_df["rank_diff"] = abs(final_df["mean_rank"] - final_df["mean_rank_vip"])
final_df["mean_rank_combined"] = (
    final_df["mean_rank"] + final_df["mean_rank_vip"]
) / 2
final_df["std_rf"] = final_df["rank_std"]
final_df["std_pls"] = final_df["std_rank_vip"]
final_df = final_df[[
    "protein",
    "mean_rank_combined",
    "std_rf",
    "std_pls",
    "vip_freq",
    "rank_diff"
]]
final_df = final_df.sort_values(by="mean_rank_combined")

In [15]:
final_df.head(20)

   protein  mean_rank_combined     std_rf    std_pls  vip_freq  rank_diff
0   P61916               1.565   1.305795   0.489898      1.00       0.73
1   P02751               3.510   3.105737   1.734935      1.00       1.22
2   P02749               4.640   2.854102   2.458679      1.00       0.86
4   P07998               6.390   5.143306   2.993393      1.00       3.06
3   P18065               7.300   5.265083   4.061662      1.00       0.06
5   P49641              10.265   6.078520   5.030417      1.00       0.39
6   P02766              10.480   6.420156   4.853205      1.00       1.12
7   Q12805              11.495  13.017200   8.231428      1.00       5.11
10  Q92876              13.745   9.633789   6.766062      1.00       3.53
9   Q9UBX5              14.235   8.611498   7.512683      1.00       0.75
11  P01023              16.370  12.058901   7.850471      1.00       2.72
12  P14618              16.445  11.182772   9.995374      1.00       2.79
8   Q16270              20.010  10.977705  20.317520      0.98      11.42
14  P33908              20.315  10.984876  12.188913      1.00       4.33
13  P23142              21.175  14.959612  21.233170      0.96       1.75
17  P54764              21.940  13.695470  10.736941      1.00       4.70
16  P08123              22.295  17.569986  10.105696      1.00       6.73
18  Q13449              26.085  14.538569  12.810507      1.00       0.77
20  O94856              30.925  18.434671  10.937349      1.00       3.61
24  P07477              31.200  20.663581  14.586967      1.00      10.44